# Generated by Django 2.1.1 on 2018-11-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='is_customer',
        ),
    ]
