# Generated by Django 2.1.3 on 2018-12-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20181202_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.RegisteredUser'),
        ),
    ]
