# Generated by Django 2.1.1 on 2018-12-02 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.RegisteredUser')),
                ('est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Establishment')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.RegisteredUser')),
                ('est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Establishment')),
            ],
        ),
    ]
